
## 该配置节点为独立的节点，有很多同学容易将这个配置放在spring的节点下，导致配置无法被识别
mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml  #注意：一定要对应mapper映射xml文件的所在路径
  type-aliases-package: com.boot.entity  # 注意：对应实体类的路径
spring:
  activemq:
    broker-url: tcp://101.200.164.217:61616
    #true 表示使用内置的MQ，false则连接服务器
    in-memory: false
    pool:
      #true表示使用连接池；false时，每发送一条数据创建一个连接
      enabled: true
      max-connections: 10
      #空闲的连接过期时间，默认为30秒
      idle-timeout: 30
      time-between-expiration-check: -1